import GenresSideBar from "@/components/Sidebar/GenresSideBar";
import React from "react";
import "./globals.css";
import style from "./page.module.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta httpEquiv="Content-Type" content="text/html; charset=utf-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={style.body}>
        <main className={style.main}>
          <GenresSideBar />
          <div className={style.contentWrapper}>{children}</div>
        </main>
      </body>
    </html>
  );
}
