import GenresSideBar from "@/components/Sidebar/GenresSideBar";
import Image from "next/image";
import React from "react";
import SearchIcon from "../../public/search.svg";
import "./globals.css";
import style from "./page.module.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta httpEquiv="Content-Type" content="text/html; charset=utf-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={style.body}>
        <main className={style.main}>
          {/* @ts-expect-error Async Server Component */}
          <GenresSideBar />
          <div className={style.search}>
            <form className={style.form}>
              <button aria-label="Search for movies" className={style.button}>
                <Image
                  src={SearchIcon}
                  width={16}
                  height={16}
                  alt="search"
                  className={style.searchIcon}
                />
              </button>
              <input className={style.input} placeholder="Search for movies" />
            </form>
          </div>
        </main>
      </body>
    </html>
  );
}
