import { SearchItemNavbar } from "@/components/SearchInput/SearchItem";
import GenresSideBar from "@/components/Sidebar/GenresSideBar";
import React from "react";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta httpEquiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="bg-stone-50 dark:bg-stone-950">
        <main className="flex min-h-screen 2xl:max-w-screen 2xl:mx-auto">
          <GenresSideBar />
          <SearchItemNavbar />
          {children}
        </main>
      </body>
    </html>
  );
}
